apiVersion: apps/v1
kind: Deployment
metadata:
    name: botauth
    labels:
        app.kubernetes.io/name: botauth
spec:
    selector:
        matchLabels:
            app.kubernetes.io/name: botauth
    template:
        metadata:
            labels:
                app.kubernetes.io/name: botauth
        spec:
            serviceAccountName: sa-green
            restartPolicy: Always
            containers:
                - name: proxy
                  image: gcr.io/sym-infosec-dev/skel:1
                  imagePullPolicy: Always
                - name: rssbot
                  image: gcr.io/sym-infosec-dev/rssbot:3
